FORMAT: 1A
HOST: https://api.paysafe.com/accountmanagement/v1

# Payout Instruction API

The Payout Instruction API provides our Independent Software Vendors (ISVs) / Partners with the ability to control the frequency of payouts to its merchants and define the payout amounts. Payout instructions submitted through the API are processed daily and paid out to merchants according to their funding schedule. The execution of these payout instructions is dependent on sufficient funds being available in the Merchant Account balance. In addition, the API response (whether successful or failed) displays the remaining Merchant Account balance for easy reconciliation for ISVs / Partners.

The benefits of this product is to allow our ISVs / Partners to circumvent any reconciliation challenges that their merchants may be presented with due to factors such as time zone differences, late business hours (e.g., bars/restaurants), irregular service policies / sales processes, etc. To take advantage of the benefits provided by the Payout Instruction API, ISVs / Partners are required to be:

+ Operating through a Managed PayFac model
+ Using Fee Redirect services
+ Able to provide direct reporting/reconciliation to their merchants

<a name="payoutinstruction" title="Payout Instruction API Overview"></a>


## Production URL

To process live requests with Paysafe, use the following Production URL:

`https://api.paysafe.com/accountmanagement/v1`

<b>For Example</b>

Payout a merchant a specified amount

`https://api.paysafe.com/accountmanagement/v1/accounts/{account_id}/payouts`

## Payout Instruction Workflow

**Payout Instruction Workflow**
![](https://raw.githubusercontent.com/paysafegroup/Payout-Instruction-API/main/Payout_Instruction.PNG)

#### Error Codes

| Error Code | HTTP Status Code   | Error Message  | Detailed Message               |
|---------|-----------------------|-----------     |--------------------------------|
| 5021    | 402 | Your transaction request has been declined. | Balance is zero.
| 5021    | 402 | Your transaction request has been declined.  | Your request has been declined due to insufficient balance.|
| 5021    | 402 | Your transaction request has been declined. | Amount is less than the minimum allowed of <b>X</b>.|
| 5021    | 402 | Your transaction request has been declined. | Amount is greater than the maximum allowed of <b>X</b>.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!!|Account is not enabled for payout requests.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!!|Payment schedule must be manual.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!!|Payments are on hold.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!! |Account is not enabled.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!!|Days in arrears are greater than 0.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!!|Account is missing a source bank account.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!! |Destination bank account is not approved.|
| 5270    | 403 | The credentials provided with the request do not have permission to access the data requested.|N/A|
| 5031    | 409 | The credentials provided with the request do not have permission to access the data requested.|Payout with merchantRefNum <b>[X]</b> is a duplicate.|
| 5068    | 400 | Either you submitted a request that is missing a mandatory field or the value of a field does not match the format expected.|Field Errors: <br>1. Amount <br>*Required Field*<br>*size must be between 1 and 256 where leading and trailing spaces are omitted*<br><br>2. merchantRefNum<br>*Required Field*<br>*must be greater than or equal to 1* (must be less than or equal to 99999999999)|

# Data Structures

## `id`

+ `id`: `25f6dadf-176a-415f-95c9-6ff39ff697ba` (string) - This is the ID returned in the response. This ID can be used for future associated requests, Example - Payouts.

    _Read Only_, _length<=36_
    
## `amount`
    
+ `amount`: `1299` (number, required) - This is the amount that the Merchant has been asked to pay.

    _max=99999999999_
    
## `merchantRefNum`
    
+ `merchantRefNum`: `1234` (string, required) - This is the merchant reference number created by the merchant and submitted as part of the request.

    _length<=255_
    
## `status`
    
+ `status`:`COMPLETED` (enum) - Status of the transaction performed.

    _Read Only_
    
    + Members
        + `COMPLETED`
        + `FAILED`

## `balance`
+ balance:`135111` (string) - Upon successful transaction, it shows the current balance of the Partner account.        

## `dupidCheck`       
+ `dupidCheck`:`false` (boolean, optional) - This validates that this request is not a duplicate. A request is considered a duplicate if the *merchantRefNum* has already been used in a previous request within the past 90 days.

    + Default: true  

## Payout Instructions [/accounts/1000316/payouts]

+ Platforms can transfer balances or initiate merchant payouts for specified amounts.
+ Sometimes a payout is split into many merchant accounts, each of which is set up to handle the payout in the way it instructed.

### Create a Payout [POST]

+ Parameters
    + account_id: `1000316` (string, required) - This is the merchant account number.
    
+ Attributes
    + Include id
    + Include amount
    + Include merchantRefNum
    + Include status
    + Include balance
    + Include dupidCheck
    
+ Request (application/json)

            {
                "amount":1299,
                "merchantRefNum": "ORDER_ID:1231"
            }

+ Response 201 (application/json)


    + Body

            {
                "id":"b32db2fb-1c6f-4cc7-b1ed-881311b30815",
                "amount":1299,
                "merchantRefNum": "ORDER_ID:1231",
                "status":"COMPLETED",
                "balance" : 135111
            }