FORMAT: 1A
HOST: https://api.paysafe.com/accountmanagement/v1

# Payout Instruction API

The purpose of the Payout Instruction API is to give partners the ability to control and regulate payouts to their merchants. 

Today, Merchants with longer business hours are unable to balance their business day receipts against Paysafe's payout amounts. This issue is due to Paysafe's settlement cutoff not being aligned with the merchant’s business day cutoff (for example, our cutoff is midnight ET, whereas a restaurant's end of business day could be 3 am ET).
Since most Independent Software Vendors (ISVs) app knows the business hours of the merchant and the amount the merchant should be paid, Paysafe has developed and released new APIs to allow ISVs to determine the merchant payout amount.

<a name="payoutinstruction" title="Payout Instruction API Overview"></a>


## Production URL

To process live requests with Paysafe, use the following Production URL:

`https://api.paysafe.com/accountmanagement/v1`

<b>For Example</b>

Payout a merchant a specified amount

`https://api.paysafe.com/accountmanagement/v1/accounts/{account_id}/payouts`

## Payout Instruction Workflow

**Payout Instruction Workflow**
![](https://raw.githubusercontent.com/paysafegroup/Payout-Instruction-API/main/Payout_Instruction.PNG)


## Examples
### Account Balance is Zero
<a name="accountbalanceiszero" title="accountbalanceiszero"></a>
<br>

```apib
{
    "id": "cb7dfe11-3834-4b15-8282-2fa5964fca9b",
    "error": {
        "code": "5021",
        "message": "Your transaction request has been declined.",
        "details": [
            "Balance is zero."
        ],
        "links": [
            {
                "rel": "errorinfo",
                "href": "https://developer.paysafe.com/en/rest-api/platforms/account-management/test-and-go-live/account-management-errors/#ErrorCode5021"
            }
        ]
    }
}
```

### Insufficient Account Balance
<a name="insufficientaccountbalance" title="insufficientaccountbalance"></a>
<br>

```apib
{
    "id": "6f07f8f9-8ac8-486f-b102-a2cc7d4cbf7b",
    "error": {
        "code": "5021",
        "message": "Your transaction request has been declined.",
        "details": [
            "Your request has been declined due to insufficient balance."
        ],
        "links": [
            {
                "rel": "errorinfo",
                "href": "https://developer.paysafe.com/en/rest-api/platforms/account-management/test-and-go-live/account-management-errors/#ErrorCode5021"
            }
        ]
    },
    "merchantRefNum": "STELLA_CANADENSIS_1633701443",
    "balance": 3997500
}
```

### Amount Less Than Minimum Payment
<a name="amountlessthanminimumpayment" title="amountlessthanminimumpayment"></a>
<br>

```apib
{
    "id": "08919050-faf0-4187-91ab-5438b31400cb",
    "error": {
        "code": "5021",
        "message": "Your transaction request has been declined.",
        "details": [
            "Amount is less than the minimum allowed of 500."
        ],
        "links": [
            {
                "rel": "errorinfo",
                "href": "https://developer.paysafe.com/en/rest-api/platforms/account-management/test-and-go-live/account-management-errors/#ErrorCode5021"
            }
        ]
    },
    "merchantRefNum": "STELLA_CANADENSIS_1633701593",
    "balance": 3997500
}
```

### Amount Greater Than Maximum Payment
<a name="amountgreaterthanmaximumpayment" title="amountgreaterthanmaximumpayment"></a>
<br>

```apib
{
    "id": "1387ff5c-fdbb-4c33-ac1e-efa2129c0ae9",
    "error": {
        "code": "5021",
        "message": "Your transaction request has been declined.",
        "details": [
            "Amount is greater than the maximum allowed of 2000."
        ],
        "links": [
            {
                "rel": "errorinfo",
                "href": "https://developer.paysafe.com/en/rest-api/platforms/account-management/test-and-go-live/account-management-errors/#ErrorCode5021"
            }
        ]
    },
    "merchantRefNum": "STELLA_CANADENSIS_1633707467",
    "balance": 3997500
}
```

### Payout Instruction is Disabled
<a name="payoutinstructiondisabled" title="payoutinstructiondisabled"></a>
<br>

```apib
{
    "id": "276b7220-da1d-4143-91b0-c0e505e501c2",
    "error": {
        "code": "5040",
        "message": "Your merchant account is not configured for the transaction you attempted !!!",
        "details": [
            "Account is not enabled for payout requests"
        ],
        "links": [
            {
                "rel": "errorinfo",
                "href": "https://developer.paysafe.com/en/rest-api/platforms/account-management/test-and-go-live/account-management-errors/#ErrorCode5040"
            }
        ]
    }
}
```
<a name="errorexample" title="errorexample"></a>

### Error Example

<b>Sample Failed Response: 402 Status Code - Payment Required</b>

```apib

{
    "error": {
        "code": "PAYOUT-1",
        "message": "Your request has been declined due to insufficient balance.",
    },
    "id": "3a406cc6-f9f5-47dd-a2e0-41ffbbf0de3e",
    "merchantRefNum": "ORDER_ID:1231",
    "balance" :799
}
```
#### Error Codes

| Error Code | HTTP Status Code   | Error Message  | Detailed Message               |
|---------|-----------------------|-----------     |--------------------------------|
| 5021    | 402 | Your transaction request has been declined. | Balance is zero.
| 5021    | 402 | Your transaction request has been declined.  | Your request has been declined due to insufficient balance.|
| 5021    | 402 | Your transaction request has been declined. | Amount is less than the minimum allowed of <b>X</b>.|
| 5021    | 402 | Your transaction request has been declined. | Amount is greater than the maximum allowed of <b>X</b>.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!!|Account is not enabled for payout requests.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!!|Payment schedule must be manual.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!!|Payments are on hold.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!! |Account is not enabled.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!!|Days in arrears are greater than 0.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!!|Account is missing a source bank account.|
| 5040    | 401 | Your merchant account is not configured for the transaction you attempted !!! |Destination bank account is not approved.|
| 5270    | 403 | The credentials provided with the request do not have permission to access the data requested.|N/A|
| 5031    | 409 | The credentials provided with the request do not have permission to access the data requested.|Payout with merchantRefNum <b>[X]</b> is a duplicate.|
| 5068    | 400 | Either you submitted a request that is missing a mandatory field or the value of a field does not match the format expected.|Field Errors: <br>1. Amount <br>*Required Field*<br>*size must be between 1 and 256 where leading and trailing spaces are omitted*<br><br>2. merchantRefNum<br>*Required Field*<br>*must be greater than or equal to 1* (must be less than or equal to 99999999999)|

# Data Structures

## `id`

+ `id`: `25f6dadf-176a-415f-95c9-6ff39ff697ba` (string) - This is the ID returned in the response. This ID can be used for future associated requests, Example - Payouts.

    _Read Only_, _length<=36_
    
## `amount`
    
+ `amount`: `1299` (number, required) - This is the amount that the Merchant has been asked to pay.

    _max=99999999999_
    
## `merchantRefNum`
    
+ `merchantRefNum`: `1234` (string, required) - This is the merchant reference number created by the merchant and submitted as part of the request.

    _length<=255_
    
## `status`
    
+ `status`:`COMPLETED` (enum) - Status of the transaction performed.

    _Read Only_
    
    + Members
        + `COMPLETED`
        + `FAILED`

## `balance`
+ balance:`135111` (string) - Upon successful transaction, it shows the current balance of the Partner account.        

## `dupidCheck`       
+ `dupidCheck`:`false` (boolean, optional) - This validates that this request is not a duplicate. A request is considered a duplicate if the *merchantRefNum* has already been used in a previous request within the past 90 days.

    + Default: true  

## Payout Instructions [/accounts/1000316/payouts]

+ Platforms can transfer balances or initiate merchant payouts for specified amounts.
+ Sometimes a payout is split into many merchant accounts, each of which is set up to handle the payout in the way it instructed.

### Create a Payout [POST]

+ Parameters
    + account_id: `1000316` (string, required) - This is the merchant account number.
    
+ Attributes
    + Include id
    + Include amount
    + Include merchantRefNum
    + Include status
    + Include balance
    + Include dupidCheck
    
+ Request (application/json)

            {
                "amount":1299,
                "merchantRefNum": "ORDER_ID:1231"
            }

+ Response 201 (application/json)


    + Body

            {
                "id":"b32db2fb-1c6f-4cc7-b1ed-881311b30815",
                "amount":1299,
                "merchantRefNum": "ORDER_ID:1231",
                "status":"COMPLETED",
                "balance" : 135111
            }